import { OpenpanelSdk } from '@openpanel/nextjs'

const NEXT_PUBLIC_OPENPANEL_DASHBOARD_CLIENT_ID = process.env.NEXT_PUBLIC_OPENPANEL_DASHBOARD_CLIENT_ID
const OPENPANEL_DASHBOARD_CLIENT_SECRET = process.env.OPENPANEL_DASHBOARD_CLIENT_SECRET

if (!NEXT_PUBLIC_OPENPANEL_DASHBOARD_CLIENT_ID) {
  throw new Error('NEXT_PUBLIC_OPENPANEL_DASHBOARD_CLIENT_ID is required')
}

if (!OPENPANEL_DASHBOARD_CLIENT_SECRET) {
  throw new Error('OPENPANEL_DASHBOARD_CLIENT_SECRET is required')
}

export const opServerClient = new OpenpanelSdk({
  clientId: NEXT_PUBLIC_OPENPANEL_DASHBOARD_CLIENT_ID,
  clientSecret: OPENPANEL_DASHBOARD_CLIENT_SECRET,
})
