import { OpenpanelSdk } from '@openpanel/nextjs'

const OPENPANEL_DASHBOARD_CLIENT_ID_SERVER = process.env.OPENPANEL_DASHBOARD_CLIENT_ID_SERVER
const OPENPANEL_DASHBOARD_CLIENT_SECRET_SERVER = process.env.OPENPANEL_DASHBOARD_CLIENT_SECRET_SERVER

if (!OPENPANEL_DASHBOARD_CLIENT_ID_SERVER) {
  throw new Error('OPENPANEL_DASHBOARD_CLIENT_ID_SERVER is required')
}

if (!OPENPANEL_DASHBOARD_CLIENT_SECRET_SERVER) {
  throw new Error('OPENPANEL_DASHBOARD_CLIENT_SECRET_SERVER is required')
}

export const opServerClient = new OpenpanelSdk({
  clientId: OPENPANEL_DASHBOARD_CLIENT_ID_SERVER,
  clientSecret: OPENPANEL_DASHBOARD_CLIENT_SECRET_SERVER,
})
