import {
  AlarmClock,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronsUpDown,
  Circle,
  CircleDashed,
  ClipboardCheck,
  ClipboardCopy,
  Dot,
  ExternalLink,
  FolderClosed,
  FolderOpen,
  Home,
  Inbox,
  List,
  ListOrdered,
  Loader2,
  type LucideProps,
  Mail,
  MailOpen,
  Menu,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Plus,
  ScrollText,
  Send,
  Settings,
  Star,
  Sun,
  Trash2,
  UserPlus,
  UserX,
  X,
} from 'lucide-react'

const icons = {
  dot: Dot,
  close: X,
  mail: Mail,
  mailOpen: MailOpen,
  home: Home,
  inbox: Inbox,
  list: List,
  menu: Menu,
  calendar: Calendar,
  moon: Moon,
  sun: Sun,
  monitor: Monitor,
  chevronsUpDown: ChevronsUpDown,
  chevronDown: ChevronDown,
  loader: Loader2,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  settings: Settings,
  clipboardCopy: ClipboardCopy,
  clipboardCheck: ClipboardCheck,
  check: Check,
  checkCircle: CheckCircle,
  checkCircle2: CheckCircle2,
  send: Send,
  folderOpen: FolderOpen,
  folderClosed: FolderClosed,
  alarmClock: AlarmClock,
  scrollText: ScrollText,
  trash: Trash2,
  externalLink: ExternalLink,
  star: Star,
  listOrdered: ListOrdered,
  userX: UserX,
  userPlus: UserPlus,
  circle: Circle,
  circleDashed: CircleDashed,
  plus: Plus,
  minus: Minus,
}

export type IconName = keyof typeof icons

type IconProps = {
  name: IconName
  className?: string
} & LucideProps

export const Icon = ({ name, className, ...restProps }: IconProps) => {
  const IconComponent = icons[name]

  return <IconComponent className={className} {...restProps} />
}
